### ISSUE TITLE
Can't fix parameter in morris

### ISSUE THREAD

**Issue by ayadlin** [JuliaDiffEq/DiffEqSensitivity.jl#47]
Sensitivity analysis (Morris) does not allows for parameter fixing -
could also be an issue in other global methods, but I have not tried yet

param_range=[[0,5],[2,4],[3,3]]
param_step=[10,10,1] # didn'r work with [10,10,0] either or [10,10,2] either

BoundsError: attempt to access 1-element StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}} at index [2]

Thanks

**Comment by Vaibhavdixit02** [comment]
I thought about this, why do you need to pass the parameter you want to keep fixed at all? I would instead rewrite my function to take lesser parameters, assigning the value that I want to keep fixed inside the function instead of passing it as an argument 
Example: 
If I have a function with 3 parameters and I want one parameter to always take a value, say 5, then I would not write

```julia
function f_original(p)
    sin(p[1])*cos(p[2])*tan(p[3])
end
```

I would instead go with
```julia
function f_original(p)
    sin(p[1])*cos(p[2])*tan(5)
end
```

Does this help?

**Comment by ayadlin** [comment]
Yes,
I thought about that.

The function I wrote is very general and in some cases a parameter will be fixed and in other cases not.
I just wanted to have a unique function to describe my pharmacology process. 
For example, if the drug is an antibody some parameters will always be 0, but if the drug is a chemical those parameters will have value.

There are 3-5 drug classes I’ll be working with, that’s why sometimes I fix some parameters and sometime others does that make sense?

I can always write individual function for each drug type, but currently I have 21 equations and 34 parameters so it’s risky :)

Thanks!

A
